/**
 * Export the town: geometry from the feeder tree, every frame from a real episode.
 *
 * The 3D mock-up must not guess how the lamps dim. Everything it draws comes out of
 * here — bus positions from `buildLayout`, and voltages, branch currents, station
 * commands and plug-in counts captured step by step out of `LiveSim` as four
 * controllers each live through the same simulated day.
 *
 *   npx tsx scripts/world-data.ts > world.json
 */

import {
  BRANCHES,
  KW_PER_PU,
  NOMINAL_LOAD_KVAR,
  NOMINAL_LOAD_KW,
  N_BUS,
  PV_BUSES,
  STATION_BUSES,
  nominalLoadPu,
} from '../src/sim/network.js';
import { LiveSim, PV_CAPACITY_KW } from '../src/sim/live.js';
import { droop, placeholderController, uncoordinated } from '../src/sim/controllers.js';
import type { Controller } from '../src/sim/controllers.js';
import { STEPS_PER_DAY, clockOf, clearSkyFraction, loadShape } from '../src/sim/profiles.js';
import { PLACES } from '../src/ui/layout.js';

const SCENARIO = { grid: 'weak' as const, loadScale: 0.5, seed: 137710 };
/** Every other five-minute step: 144 frames a day is smooth enough to watch. */
const FRAME_STRIDE = 2;

const sacLag = placeholderController({
  id: 'sac-lag',
  label: 'SAC-Lag (plain deep RL)',
  eagerness: 0.85,
  backoffPu: 0.952,
  arbitrage: true,
  usesProjection: false,
});

const safeSac = placeholderController({
  id: 'safesac',
  label: 'SafeSAC',
  eagerness: 0.95,
  backoffPu: 0.948,
  arbitrage: false,
  usesProjection: true,
});

/**
 * Current magnitude in every branch, pu, accumulated from the leaves inward.
 * Reconstructed from the injections the step actually ran with, so it is the real
 * flow rather than a difference of voltage magnitudes.
 */
function branchCurrents(step: number, stationKw: readonly number[], vMag: Float64Array): number[] {
  const { p, q } = nominalLoadPu(loadShape(step) * SCENARIO.loadScale);
  const solar = clearSkyFraction(step) * PV_CAPACITY_KW;
  for (const bus of PV_BUSES) p[bus] -= solar / KW_PER_PU;
  STATION_BUSES.forEach((bus, i) => {
    p[bus] += stationKw[i] / KW_PER_PU;
  });

  // Children first, so a branch is only closed once everything below it is counted.
  const parent = new Int32Array(N_BUS + 1).fill(0);
  const rOf = new Float64Array(N_BUS + 1);
  const xOf = new Float64Array(N_BUS + 1);
  const Z_BASE = (12.66 * 12.66) / 10;
  for (const b of BRANCHES) {
    parent[b.to] = b.from;
    rOf[b.to] = b.rOhm / Z_BASE;
    xOf[b.to] = b.xOhm / Z_BASE;
  }

  const out: number[] = [];
  const order = [...Array(N_BUS + 1).keys()].slice(2);
  order.sort((a, c) => depth(c) - depth(a));
  const current = new Map<number, number>();
  for (const bus of order) {
    const v = Math.max(1e-6, vMag[bus]);
    const iMag = Math.hypot(p[bus], q[bus]) / v;
    current.set(bus, iMag);
    const up = parent[bus];
    if (up >= 1) {
      p[up] += p[bus] + iMag * iMag * rOf[bus];
      q[up] += q[bus] + iMag * iMag * xOf[bus];
    }
  }
  for (const b of BRANCHES) out.push(Number((current.get(b.to) ?? 0).toFixed(5)));
  return out;

  function depth(bus: number): number {
    let d = 0;
    let cur = bus;
    while (cur > 1 && d < 64) {
      cur = parent[cur];
      d++;
    }
    return d;
  }
}

function capture(controller: Controller, projection: boolean) {
  const sim = new LiveSim(SCENARIO);
  controller.reset?.();
  const frames: unknown[] = [];

  while (!sim.finished) {
    const step = sim.step;
    const plugged = sim.capabilities.map((c) => c.connected);
    const record = sim.advanceWith(controller, projection);
    if (step % FRAME_STRIDE !== 0) continue;

    frames.push({
      t: step,
      clock: clockOf(step),
      v: Array.from({ length: N_BUS + 1 }, (_, b) => Number(record.voltages[b].toFixed(4))),
      i: branchCurrents(step, record.safeKw, record.voltages),
      kw: record.safeKw.map((k) => Number(k.toFixed(1))),
      raw: record.rawKw.map((k) => Number(k.toFixed(1))),
      plugged,
      solar: Number(record.solarKw.toFixed(1)),
      loss: Number(record.lossKw.toFixed(2)),
      viol: record.violations,
      vmin: Number(record.vMin.toFixed(4)),
      vminBus: record.vMinBus,
    });
  }

  const totals = sim.finalTotals();
  return {
    id: controller.id,
    label: controller.label,
    provenance: controller.provenance,
    projection,
    violationRate: Number(totals.violationRate.toFixed(4)),
    socMet: Number(totals.socMet.toFixed(4)),
    totalLossKwh: Number(totals.totalLossKwh.toFixed(1)),
    netCostUsd: Number(totals.netCostUsd.toFixed(0)),
    vMinPu: Number(totals.vMinPu.toFixed(4)),
    frames,
  };
}

const world = {
  note: 'Generated by scripts/world-data.ts from the IEEE 33-bus weak feeder. Do not hand-edit.',
  scenario: SCENARIO,
  stepsPerDay: STEPS_PER_DAY,
  frameStride: FRAME_STRIDE,
  places: PLACES.map((p) => ({
    bus: p.bus,
    col: p.col,
    row: p.row,
    houses: p.houses,
    kw: NOMINAL_LOAD_KW[p.bus],
    kvar: NOMINAL_LOAD_KVAR[p.bus],
  })),
  // Resistance travels with the branch so the viewer can turn a current into the
  // heat actually going into that conductor, which is the quantity the
  // sustainability story is about.
  branches: BRANCHES.map((b) => ({
    from: b.from,
    to: b.to,
    rPu: Number((b.rOhm / ((12.66 * 12.66) / 10)).toFixed(6)),
  })),
  stations: STATION_BUSES,
  pv: PV_BUSES,
  runs: [
    capture(uncoordinated, false),
    capture(droop, false),
    capture(sacLag, false),
    capture(safeSac, true),
  ],
};

console.log(JSON.stringify(world));
